### ISSUE TITLE
Failed to open any amiga font

### ISSUE THREAD

**Issue by Sembiance** [smugpie/amiga-bitmap-font-tools#2]
Attempting to open any amiga font, and convert to any format, yields this error:

```
(python) sembiance@lostcrag ~/ $ python3 openAmigaFont.py -i ../fonts/native/Magnet.font -o test.otf -f otf
Traceback (most recent call last):
  File "/home/sembiance/Downloads/amiga-bitmap-font-tools/python/openAmigaFont.py", line 186, in <module>
    main(sys.argv[1:])
  File "/home/sembiance/Downloads/amiga-bitmap-font-tools/python/openAmigaFont.py", line 92, in main
    fontBitmapRows = list(chunks(fontBitArray, modulo * 8))
  File "/home/sembiance/Downloads/amiga-bitmap-font-tools/python/utils.py", line 6, in chunks
    for i in range(0, len(lst), n):
ValueError: range() arg 3 must not be zero
```

Running `python 3.9.9` with `fontparts 0.10.2` and `fontmake 3.1.1`

Parsing the same font with `node/readFontContents.js` works just fine.

**Comment by smugpie** [comment]
Hi! This script works on the individual font files in the font folders only. (The `Magnet.font` file is just a list of contents of all the fonts in the Magnet folder) 

So the following should work: `python3 openAmigaFont.py -i ../fonts/native/Magnet/32 -o test.otf -f otf`

Hope this helps!

**Comment by smugpie** [comment]
I should maybe add some decent error messages!

**Comment by Sembiance** [comment]
Ahh, I got it now. It works. I think just adding a note to the python/README.md file that the `input file` is one of the files from the directory, and not the .font file itself would be plenty enough to avoid any future confusion.

Thanks for letting me know how it works and thanks for creating the script :)
