### ISSUE TITLE
ValueError: range() arg 3 must not be zero

### ISSUE THREAD

**Issue by a-rabin** [smugpie/amiga-bitmap-font-tools#3]
Hello,
I followed the instructions but when I ran the command to convert a font file to ttf i get this traceback error:

```
Traceback (most recent call last):
  File "F:\Programming\amiga-bitmap-font-tools\python\openAmigaFont.py", line 18
6, in <module>
    main(sys.argv[1:])
  File "F:\Programming\amiga-bitmap-font-tools\python\openAmigaFont.py", line 92
, in main
    fontBitmapRows = list(chunks(fontBitArray, modulo * 8))
  File "F:\Programming\amiga-bitmap-font-tools\python\utils.py", line 6, in chun
ks
    for i in range(0, len(lst), n):
ValueError: range() arg 3 must not be zero
```
Any fixes?

**Comment by smugpie** [comment]
Hi! And thanks for trying this out! Take a look at https://github.com/smugpie/amiga-bitmap-font-tools/issues/2 to see if that resolves the issue. (TLDR: run the tool on the fonts inside the folder and not the .font file itself). I’ll try and come up with a better error message one day.

**Comment by a-rabin** [comment]
okay it worked! thanks!
