### ISSUE TITLE
"Futura" font fails to convert

### ISSUE THREAD

**Issue by dude22072** [smugpie/amiga-bitmap-font-tools#7]
The font "Futura" contained in https://aminet.net/package/text/bfont/Custom3 produces a font file that windows claims is invalid.

**Comment by smugpie** [comment]
Oh wait! I can see the font name 'Futura' isn't picked up properly. I'll see if this can be fixed.

**Comment by smugpie** [comment]
I've put a temporary fix in so that the font name falls back to 'AmigaFont' if it can't find the font name in the file. I'll put a better fix in based on directory name when I have a moment. But, for now, let me know if the font is now recognised on Windows. Thanks!

**Comment by smugpie** [comment]
And now I've put in a further fix that takes the parent directory name. Hope this works for you!

**Comment by dude22072** [comment]
Converts properly now 👍

**Comment by smugpie** [comment]
Thanks for closing! I couldn't resist adding a parameter to control the aspect ratio to make the font narrower and more like Futura. 
<img width="788" alt="image" src="https://github.com/smugpie/amiga-bitmap-font-tools/assets/731783/885384e8-0872-4ae8-9208-d33da60370c3">
